# Generated by Django 3.0.8 on 2021-05-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_auto_20210517_1906")]

    operations = [
        migrations.RenameField(model_name="account", old_name="user_id", new_name="id")
    ]
