# Generated by Django 3.0.8 on 2021-05-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0003_auto_20210517_1912")]

    operations = [migrations.AlterModelManagers(name="account", managers=[])]
