# Generated by Django 3.0.8 on 2021-05-19 19:12

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_auto_20210518_0553")]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[("objects", django.contrib.auth.models.UserManager())],
        )
    ]
