{
 "title": "Game portal dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Game Portal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request per min",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_view_transport_method_total{view!=\"prometheus-django-metrics\"}[5m]) * 60"
    }
   ]
  },
  {
   "title": "Latency by View",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{view!=\"prometheus-django-metrics\"}[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count{view!=\"prometheus-django-metrics\"}[5m]) "
    }
   ]
  },
  {
   "title": "Responses By View and Status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_view_method_total{view!=\"prometheus-django-metrics\"}[1m])"
    }
   ]
  },
  {
   "title": "Game Portal Non-200 responses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_total{status!=\"200\", status!=\"201\"}[5m])"
    }
   ]
  },
  { "title": "RPS Game Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Active Games",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "game_rps_active_games_total" }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(game_rps_active_connections_total[5m])"
    }
   ]
  },
  {
   "title": "Socekt msgs per min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(game_rps_socket_messages_received[5m]) * 60 "
    }
   ]
  },
  { "title": "Matchmaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Request Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(matchmaker_server_http_request_duration_seconds_sum[5m]) / rate(matchmaker_server_http_request_duration_seconds_count[5m])) * 60"
    }
   ]
  },
  {
   "title": "Matchmaker Requests per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(matchmaker_server_http_request_total[5m]) * 60"
    }
   ]
  },
  {
   "title": "Matchmaker events processed per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmaker_worker_events_processed_total[1m])"
    }
   ]
  },
  {
   "title": "Matchmaker Worker event batch processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmaker_worker_execution_time_sum[1m]) / rate(matchmaker_worker_execution_time_count[1m])"
    }
   ]
  },
  { "title": "Stats Tracker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stats_server_http_request_total[5m]) * 60"
    }
   ]
  },
  {
   "title": "API Request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(stats_server_http_request_duration_seconds_sum[5m]) / rate(stats_server_http_request_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Stats tracker events processed per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stats_worker_events_processed_total[1m])"
    }
   ]
  },
  {
   "title": "Task processing latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(stats_worker_execution_time_sum[5m]) / rate(stats_worker_execution_time_count[5m]))"
    }
   ]
  }
 ]
}