FROM python:3.8-alpine
ENV PYTHONUNBUFFERED 1

RUN apk add bash
RUN apk add vim
RUN apk add redis
RUN apk add build-base

RUN mkdir /stats_tracker
WORKDIR /stats_tracker

ADD stats_tracker ./stats_tracker
ADD tests ./tests/

ADD requirements.txt ./
ADD requirements_test.txt ./
ADD requirements_dev.txt ./

RUN pip install --upgrade pip && pip install -r requirements.txt
RUN pip install -r requirements_test.txt
RUN pip install -r requirements_dev.txt

CMD redis-server