# Generated by Django 3.0.8 on 2021-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_state",
            field=models.CharField(
                choices=[("ACT", "Active"), ("INA", "Inactive"), ("CMS", "ComingSoon")],
                default="INA",
                max_length=3,
            ),
        ),
    ]
