# Generated by Django 3.1.12 on 2021-07-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_game_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="banner_art",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
