# Generated by Django 3.1.12 on 2021-07-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_banner_art"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="translations",
            field=models.FileField(null=True, upload_to="data"),
        ),
    ]
