# Generated by Django 3.1.12 on 2021-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="translations",
            field=models.FileField(null=True, upload_to="strings"),
        ),
    ]
