# Generated by Django 3.1.12 on 2021-07-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_auto_20210724_0713"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="translations",
        ),
        migrations.AddField(
            model_name="game",
            name="stats_config",
            field=models.FileField(null=True, upload_to="stats_config"),
        ),
    ]
