# Generated by Django 3.1.12 on 2021-09-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20210729_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='banner_art',
        ),
    ]
