# Generated by Django 3.0.8 on 2021-05-17 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=30)),
                ("level", models.IntegerField(default=1)),
                ("xp", models.IntegerField(default=0)),
            ],
        )
    ]
