# Generated by Django 3.1.12 on 2021-09-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=30)),
                ("level", models.IntegerField(default=1)),
                ("xp", models.IntegerField(default=0)),
            ],
        ),
    ]
